title: Tuan Nguyen
url: "tuanrpt.github.io"
baseurl: ""

markdown: kramdown
# ins_logo: "imgs/monash-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Based on the code of Ankit Sultana"

# remote_theme: ankitsultana/researcher@gem

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Google Scholar"
   link: "https://scholar.google.com/citations?hl=en&user=DPsUJFgAAAAJ&view_op=list_works&sortby=pubdate"
 - name: "Github"
   link: "https://github.com/tuanrpt"
